# netlify.toml

[build]
  command = "npm install"
  publish = "." 

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/birthdays/:splat"
  status = 200
